### PR TITLE
Update build dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `2.14.1` and all Android deps to `24`. [UPDATE See below: PR now contains more recent dependencies]
[UPDATE 2]
PR now includes latest Gradle wrapper 3.3 and latest Android build tools.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Updated to Gradle wrapper `2.14.1` and rebase. Circle CI does not seem to support android-24 yet which is why the build is failing.

**Comment by friederbluemle** [comment]
Build is now passing.

**Comment by friederbluemle** [comment]
Updated again to the latest dependencies:

- Android Gradle plugin 2.2.0
- Gradle wrapper 3.1

This is now compatible with the latest stable Android Studio 2.2

Also updated `minSdkLevel` to 9 - This is because of the appcompat-v7 dependency: `uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library [com.android.support:appcompat-v7:24.2.1]`

**Comment by friederbluemle** [comment]
@kobakei I just rebased this, and it was quite painful, since you coincidentally made many similar changes to the `master` branch on the same day. The branch now builds again, and contains the remaining fixes and updates.

**Comment by kobakei** [comment]
Sorry, I have updated SDK version and support lib so I close this PR.

**Comment by friederbluemle** [comment]
Hmm well you could've just left this PR open, and would have removed the commits with the changes you already made on master. This PR contained more than "just" the SDK version update.

**Pull request closed without merging**
